### ISSUE TITLE
save settings

### ISSUE THREAD

**Issue by pepijndevos** [badgeteam/esp32-component-bme680#2]
https://github.com/BoschSensortec/BSEC-Arduino-library/blob/master/examples/basic_config_state/basic_config_state.ino
https://github.com/badgeteam/mch2022-firmware-esp32/blob/master/main/settings.c

**Comment by renzenicolai** [comment]
The state that is being saved is the internal state of the closed source bsec library. This driver avoids the use of that blob and thus doesn't need to save any state.

Feel free to create an additional driver that adds BSEC on top of this driver, but I strongly recommend against adding the closed source library to the base driver as it's not needed unless you want to convert the measurements over time to an air quality measurement.
